// Mapping of technology names to Devicon CSS classes (all lowercase keys)
export const techIconMap: Record<string, string> = {
  // Programming Languages
  javascript: 'devicon-javascript-plain',
  js: 'devicon-javascript-plain',
  typescript: 'devicon-typescript-plain',
  ts: 'devicon-typescript-plain',
  python: 'devicon-python-plain',
  java: 'devicon-java-plain',
  golang: 'devicon-go-plain',
  go: 'devicon-go-plain',
  rust: 'devicon-rust-plain',
  'c++': 'devicon-cplusplus-plain',
  cpp: 'devicon-cplusplus-plain',
  c: 'devicon-c-plain',
  'c#': 'devicon-csharp-plain',
  csharp: 'devicon-csharp-plain',
  php: 'devicon-php-plain',
  ruby: 'devicon-ruby-plain',
  swift: 'devicon-swift-plain',
  kotlin: 'devicon-kotlin-plain',
  dart: 'devicon-dart-plain',
  scala: 'devicon-scala-plain',
  elixir: 'devicon-elixir-plain',
  clojure: 'devicon-clojure-plain',
  haskell: 'devicon-haskell-plain',
  bash: 'devicon-bash-plain',
  shell: 'devicon-bash-plain',
  powershell: 'devicon-powershell-plain',
  solidity: 'devicon-solidity-plain',
  zig: 'devicon-zig-plain',
  gleam: 'devicon-gleam-plain',
  julia: 'devicon-julia-plain',
  r: 'devicon-r-plain',
  matlab: 'devicon-matlab-plain',
  perl: 'devicon-perl-plain',
  cobol: 'devicon-cobol-plain',
  fortran: 'devicon-fortran-plain',

  // Frontend Frameworks & Libraries
  react: 'devicon-react-original',
  reactjs: 'devicon-react-original',
  vue: 'devicon-vuejs-plain',
  vuejs: 'devicon-vuejs-plain',
  angular: 'devicon-angularjs-plain',
  svelte: 'devicon-svelte-plain',
  'next.js': 'devicon-nextjs-plain',
  nextjs: 'devicon-nextjs-plain',
  nuxt: 'devicon-nuxtjs-plain',
  nuxtjs: 'devicon-nuxtjs-plain',
  astro: 'devicon-astro-plain',
  remix: 'devicon-remix-plain',
  solidjs: 'devicon-solidjs-plain',
  solid: 'devicon-solidjs-plain',
  qwik: 'devicon-qwik-plain',
  alpinejs: 'devicon-alpinejs-plain',
  alpine: 'devicon-alpinejs-plain',
  htmx: 'devicon-htmx-plain',
  backbone: 'devicon-backbonejs-plain',
  backbonejs: 'devicon-backbonejs-plain',
  ember: 'devicon-ember-original-wordmark',
  gatsby: 'devicon-gatsby-plain',

  // UI & Styling Libraries
  tailwind: 'devicon-tailwindcss-plain',
  tailwindcss: 'devicon-tailwindcss-plain',
  bootstrap: 'devicon-bootstrap-plain',
  sass: 'devicon-sass-original',
  scss: 'devicon-sass-original',
  less: 'devicon-less-plain-wordmark',
  shadcn: 'devicon-tailwindcss-plain', // Fallback, uses tailwindcss and react
  shadcnui: 'devicon-tailwindcss-plain',
  'shadcn ui': 'devicon-tailwindcss-plain',
  'shadcn/ui': 'devicon-tailwindcss-plain',
  radix: 'devicon-react-original', // Fallback
  radixui: 'devicon-react-original',
  'radix ui': 'devicon-react-original',
  chakra: 'devicon-chakraui-plain',
  chakraui: 'devicon-chakraui-plain',
  'chakra ui': 'devicon-chakraui-plain',
  materialui: 'devicon-materialui-plain',
  'material-ui': 'devicon-materialui-plain',
  'material ui': 'devicon-materialui-plain',
  mui: 'devicon-materialui-plain',
  vuetify: 'devicon-vuetify-plain',
  primeng: 'devicon-primeng-plain',
  primevue: 'devicon-vuejs-plain',
  primereact: 'devicon-react-original',
  antdesign: 'devicon-antdesign-plain',
  'ant design': 'devicon-antdesign-plain',
  antd: 'devicon-antdesign-plain',
  angularmaterial: 'devicon-angularmaterial-plain',
  'angular material': 'devicon-angularmaterial-plain',
  reactbootstrap: 'devicon-reactbootstrap-original',
  'react-bootstrap': 'devicon-reactbootstrap-original',
  'react bootstrap': 'devicon-reactbootstrap-original',
  bulma: 'devicon-bulma-plain',
  foundation: 'devicon-foundation-plain',
  headlessui: 'devicon-tailwindcss-plain',
  'headless ui': 'devicon-tailwindcss-plain',
  daisyui: 'devicon-tailwindcss-plain',
  'daisy ui': 'devicon-tailwindcss-plain',

  // Backend & Runtime
  'node.js': 'devicon-nodejs-plain',
  nodejs: 'devicon-nodejs-plain',
  express: 'devicon-express-original',
  expressjs: 'devicon-express-original',
  fastapi: 'devicon-fastapi-plain',
  flask: 'devicon-flask-original',
  django: 'devicon-django-plain',
  spring: 'devicon-spring-plain',
  'spring boot': 'devicon-spring-plain',
  laravel: 'devicon-laravel-plain',
  rails: 'devicon-rails-plain',
  'ruby on rails': 'devicon-rails-plain',
  fastify: 'devicon-fastify-plain',
  nestjs: 'devicon-nestjs-plain',
  nest: 'devicon-nestjs-plain',
  trpc: 'devicon-trpc-plain',
  grpc: 'devicon-grpc-plain',
  graphql: 'devicon-graphql-plain',
  apollo: 'devicon-apollographql-plain',
  apollographql: 'devicon-apollographql-plain',
  'apollo graphql': 'devicon-apollographql-plain',
  bun: 'devicon-bun-plain',
  deno: 'devicon-denojs-plain',
  denojs: 'devicon-denojs-plain',

  // DevOps & Infrastructure (including Cloud Services)
  docker: 'devicon-docker-plain',
  kubernetes: 'devicon-kubernetes-plain',
  k8s: 'devicon-kubernetes-plain',
  aws: 'devicon-amazonwebservices-original',
  'amazon web services': 'devicon-amazonwebservices-original',
  gcp: 'devicon-googlecloud-plain',
  'google cloud': 'devicon-googlecloud-plain',
  'google cloud platform': 'devicon-googlecloud-plain',
  'cloud run': 'devicon-cloudrun-plain',
  'google cloud run': 'devicon-cloudrun-plain',
  cloudrun: 'devicon-cloudrun-plain',
  'cloud storage': 'devicon-googlecloud-plain',
  'google cloud storage': 'devicon-googlecloud-plain',
  gcs: 'devicon-googlecloud-plain',
  bigquery: 'devicon-googlecloud-plain',
  'google cloud bigquery': 'devicon-googlecloud-plain',
  'cloud functions': 'devicon-googlecloud-plain',
  'google cloud functions': 'devicon-googlecloud-plain',
  gke: 'devicon-kubernetes-plain',
  'google kubernetes engine': 'devicon-kubernetes-plain',
  gce: 'devicon-googlecloud-plain',
  'compute engine': 'devicon-googlecloud-plain',
  'google compute engine': 'devicon-googlecloud-plain',
  'app engine': 'devicon-googlecloud-plain',
  'google app engine': 'devicon-googlecloud-plain',
  'cloud sql': 'devicon-googlecloud-plain',
  'google cloud sql': 'devicon-googlecloud-plain',
  'pub/sub': 'devicon-googlecloud-plain',
  pubsub: 'devicon-googlecloud-plain',
  'google cloud pubsub': 'devicon-googlecloud-plain',
  'cloud build': 'devicon-googlecloud-plain',
  'google cloud build': 'devicon-googlecloud-plain',
  'cloud deploy': 'devicon-googlecloud-plain',
  'google cloud deploy': 'devicon-googlecloud-plain',
  colab: 'devicon-googlecolab-plain',
  'google colab': 'devicon-googlecolab-plain',
  googlecolab: 'devicon-googlecolab-plain',
  firebase: 'devicon-firebase-plain',
  firestore: 'devicon-firebase-plain',
  'cloud firestore': 'devicon-firebase-plain',
  'firebase firestore': 'devicon-firebase-plain',
  'firebase hosting': 'devicon-firebase-plain',
  'firebase functions': 'devicon-firebase-plain',
  'firebase auth': 'devicon-firebase-plain',
  dynamodb: 'devicon-dynamodb-plain',
  s3: 'devicon-amazonwebservices-original',
  ec2: 'devicon-amazonwebservices-original',
  lambda: 'devicon-amazonwebservices-original',
  'aws lambda': 'devicon-amazonwebservices-original',
  rds: 'devicon-amazonwebservices-original',
  'azure devops': 'devicon-azuredevops-plain',
  azuredevops: 'devicon-azuredevops-plain',
  'azure sql': 'devicon-azuresqldatabase-plain',
  azure: 'devicon-azure-plain',
  'microsoft azure': 'devicon-azure-plain',
  vercel: 'devicon-vercel-plain',
  netlify: 'devicon-netlify-plain',
  heroku: 'devicon-heroku-plain',
  terraform: 'devicon-terraform-plain',
  ansible: 'devicon-ansible-plain',
  pulumi: 'devicon-pulumi-plain',
  'github actions': 'devicon-githubactions-plain',
  githubactions: 'devicon-githubactions-plain',
  jenkins: 'devicon-jenkins-plain',
  circleci: 'devicon-circleci-plain',
  argocd: 'devicon-argocd-plain',
  prometheus: 'devicon-prometheus-plain',
  grafana: 'devicon-grafana-plain',
  datadog: 'devicon-datadog-plain',
  sentry: 'devicon-sentry-plain',
  nginx: 'devicon-nginx-original',
  apache: 'devicon-apache-plain',
  cloudflare: 'devicon-cloudflare-plain',
  cloudflareworkers: 'devicon-cloudflareworkers-plain',
  'cloudflare workers': 'devicon-cloudflareworkers-plain',
  supabase: 'devicon-supabase-plain',

  // Databases
  mongodb: 'devicon-mongodb-plain',
  mongo: 'devicon-mongodb-plain',
  postgresql: 'devicon-postgresql-plain',
  postgres: 'devicon-postgresql-plain',
  mysql: 'devicon-mysql-plain',
  redis: 'devicon-redis-plain',
  sqlite: 'devicon-sqlite-plain',
  cassandra: 'devicon-cassandra-plain',
  couchdb: 'devicon-couchdb-plain',
  mariadb: 'devicon-mariadb-plain',
  neo4j: 'devicon-neo4j-plain',
  oracle: 'devicon-oracle-original',
  prisma: 'devicon-prisma-original',
  sequelize: 'devicon-sequelize-plain',
  mongoose: 'devicon-mongoose-plain',

  // Version Control & Tools
  git: 'devicon-git-plain',
  github: 'devicon-github-original',
  gitlab: 'devicon-gitlab-plain',
  'visual studio code': 'devicon-vscode-plain',
  vscode: 'devicon-vscode-plain',
  'vs code': 'devicon-vscode-plain',
  gitbook: 'devicon-gitbook-plain',
  gitpod: 'devicon-gitpod-plain',
  trello: 'devicon-trello-plain',
  notion: 'devicon-notion-plain',
  slack: 'devicon-slack-plain',
  discord: 'devicon-discord-plain',
  postman: 'devicon-postman-plain',
  insomnia: 'devicon-insomnia-plain',

  // Package Managers & Build Tools
  webpack: 'devicon-webpack-plain',
  vite: 'devicon-vite-plain',
  npm: 'devicon-npm-original-wordmark',
  yarn: 'devicon-yarn-plain',
  pnpm: 'devicon-pnpm-plain',
  homebrew: 'devicon-homebrew-plain',
  rollup: 'devicon-rollup-plain',
  babel: 'devicon-babel-plain',
  eslint: 'devicon-eslint-plain',
  biome: 'devicon-biome-plain',

  // Testing
  jest: 'devicon-jest-plain',
  playwright: 'devicon-playwright-plain',
  cypress: 'devicon-cypressio-plain',
  cypressio: 'devicon-cypressio-plain',
  vitest: 'devicon-vitest-plain',
  mocha: 'devicon-mocha-plain',
  jasmine: 'devicon-jasmine-plain',

  // Operating Systems
  linux: 'devicon-linux-plain',
  ubuntu: 'devicon-ubuntu-plain',
  debian: 'devicon-debian-plain',
  centos: 'devicon-centos-plain',
  windows: 'devicon-windows8-original',

  // Mobile Development
  android: 'devicon-android-plain',
  ios: 'devicon-apple-original',
  flutter: 'devicon-flutter-plain',
  ionic: 'devicon-ionic-original',
  'react native': 'devicon-reactnative-plain',
  reactnative: 'devicon-reactnative-plain',
  expo: 'devicon-expo-plain',
  xcode: 'devicon-xcode-plain',
  androidstudio: 'devicon-androidstudio-plain',
  'android studio': 'devicon-androidstudio-plain',

  // Design Tools
  figma: 'devicon-figma-plain',
  canva: 'devicon-canva-plain',
  photoshop: 'devicon-photoshop-plain',
  illustrator: 'devicon-illustrator-plain',
  'premiere pro': 'devicon-premierepro-plain',
  premiere: 'devicon-premierepro-plain',
  'after effects': 'devicon-aftereffects-plain',
  aftereffects: 'devicon-aftereffects-plain',
  blender: 'devicon-blender-original',
  sketch: 'devicon-sketch-line',

  // Markup & Data Formats
  html: 'devicon-html5-plain',
  html5: 'devicon-html5-plain',
  css: 'devicon-css3-plain',
  css3: 'devicon-css3-plain',

  // Additional tags from projects
  api: 'devicon-openapi-plain',
  'web scraping': 'devicon-webpack-plain',
  'data processing': 'devicon-azuresqldatabase-plain',
}

/**
 * Get the Devicon CSS class for a given technology tag
 * @param tag - The technology tag (case-insensitive)
 * @returns The corresponding Devicon CSS class or null if not found
 */
export function getTechIconClass(tag: string): string | null {
  return techIconMap[tag.toLowerCase()] || null
}

/**
 * Check if a technology tag has an associated icon
 * @param tag - The technology tag
 * @returns true if an icon exists for the tag
 */
export function hasTechIcon(tag: string): boolean {
  return getTechIconClass(tag) !== null
}

/**
 * Get all available technology tags that have icons
 * @returns Array of technology tag names
 */
export function getAvailableTechTags(): string[] {
  return Object.keys(techIconMap)
}